(()=>{"use strict";
const app=document.querySelector("#app"),picker=document.querySelector("#bank-picker"),LS="electrician-private-v2",DB="electrician-private-banks";
let state=JSON.parse(localStorage.getItem(LS)||'{"records":[],"wrong":[],"session":null,"notionUrl":""}'),tick=null;
const subjects=["전기자기학","전력공학","전기기기","회로이론 및 제어공학","전기설비기술기준"];
const save=()=>localStorage.setItem(LS,JSON.stringify(state));
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function toast(m){const e=document.querySelector("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore("banks",{keyPath:"id"});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function tx(mode,fn){const db=await openDb();return new Promise((ok,no)=>{const t=db.transaction("banks",mode),s=t.objectStore("banks"),r=fn(s);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
const getBank=id=>tx("readonly",s=>s.get(id));
const allBanks=()=>tx("readonly",s=>s.getAll());
const putBank=b=>tx("readwrite",s=>s.put(b));
const delBank=id=>tx("readwrite",s=>s.delete(id));
async function decodeBank(file){const raw=await file.arrayBuffer();let text;try{const stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream("gzip"));text=await new Response(stream).text()}catch{text=new TextDecoder().decode(raw)}const bank=JSON.parse(text);if(bank.version!==1||!bank.id||!Array.isArray(bank.questions))throw Error("지원하지 않는 은행 파일");return bank}
async function route(view,data){clearInterval(tick);tick=null;window.scrollTo(0,0);if(view==="home")return home();if(view==="banks")return banks();if(view==="records")return records();if(view==="settings")return settings();if(view==="quiz")return quiz();if(view==="result")return result(data)}
document.addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)route(b.dataset.view)});
function dday(){const d=Math.ceil((new Date("2026-09-01T00:00:00+09:00")-new Date())/864e5);document.querySelector("#dday").textContent=d>=0?`D-${d}`:`D+${-d}`}
async function home(){const bs=await allBanks(),count=bs.reduce((n,b)=>n+b.questions.length,0);app.innerHTML=`<section class="hero"><span class="pill">비공개 · 기기 내 저장</span><h1>실제 복원 기출만<br>문제처럼 풀기</h1><p>공개 앱에는 문항이 없습니다. 본인의 .bank 파일을 불러오면 IndexedDB에만 저장됩니다.</p></section><div class="grid"><button class="card primary" id="import"><strong>기출 파일 불러오기</strong><small>${bs.length}개 회차 · ${count}문항 저장됨</small></button><button class="card" data-view="banks"><strong>회차별 풀기</strong><small>수록 문항 그대로</small></button><button class="card" id="mock"><strong>100문항 실전</strong><small>과목별 20 · 150분</small></button><button class="card" id="wrong"><strong>오답 다시 풀기</strong><small>${state.wrong.length}문항</small></button><button class="card wide" id="subject"><strong>과목별 랜덤</strong><small>선택 과목 20문항 · 30분</small></button></div><div class="notice"><b>저작권 보호 구조</b><br>PDF·OCR·기출 이미지는 GitHub에 올라가지 않습니다. 결과 Markdown에는 문항 본문 대신 회차·번호·선택·정답만 기록됩니다.</div>`;
app.querySelector("#import").onclick=()=>picker.click();app.querySelector("#mock").onclick=startMock;app.querySelector("#wrong").onclick=startWrong;app.querySelector("#subject").onclick=startSubject}
picker.onchange=async()=>{let n=0;for(const file of picker.files){try{const b=await decodeBank(file);await putBank(b);n++}catch(e){toast(`${file.name}: ${e.message}`)}}picker.value="";toast(`${n}개 회차 저장 완료`);route("banks")};
async function banks(){const bs=(await allBanks()).sort((a,b)=>b.year-a.year||a.round-b.round);app.innerHTML=`<h1>실제 기출 회차</h1><p class="muted">PDF에 삭제된 번호는 채우거나 창작하지 않고 실제 수록분만 표시합니다.</p><button class="action primary" id="import">＋ .bank 파일 불러오기</button><div class="bank-list">${bs.length?bs.map(b=>`<button class="bank" data-bank="${esc(b.id)}"><span><strong>${esc(b.label)}</strong><small>${b.questions.filter(q=>q.answer).length}문항 자동채점 · ${b.questions.length-b.questions.filter(q=>q.answer).length}문항 정답표식 검수대기</small></span><span class="count">${b.questions.length}</span></button>`).join(""):'<div class="notice">아직 저장된 회차가 없습니다. 전달된 private-banks 폴더의 파일을 선택하세요.</div>'}</div>`;app.querySelector("#import").onclick=()=>picker.click();app.querySelectorAll("[data-bank]").forEach(x=>x.onclick=async()=>{const b=await getBank(x.dataset.bank);startSession(b.label,b.questions.map((q,i)=>({bankId:b.id,index:i})),b.questions.length<=20?1800:9000)})}
function startSession(title,refs,seconds){state.session={title,refs,answers:{},current:0,startedAt:Date.now(),seconds};save();route("quiz")}
async function startMock(){const bs=await allBanks();if(!bs.length)return toast("먼저 기출 파일을 불러오세요");let refs=[];for(let s=0;s<5;s++){let pool=[];bs.forEach(b=>b.questions.forEach((q,i)=>{if(q.subject===s&&q.answer)pool.push({bankId:b.id,index:i})}));pool.sort(()=>Math.random()-.5);refs.push(...pool.slice(0,20))}if(refs.length<100)return toast("과목별 20문항을 만들 자료가 부족합니다");refs.sort(()=>Math.random()-.5);startSession("실제 기출 랜덤 실전 100",refs,9000)}
async function startSubject(){const name=prompt(`과목 번호를 입력하세요.\n${subjects.map((s,i)=>`${i+1}. ${s}`).join("\n")}`,"1"),s=Number(name)-1;if(s<0||s>4)return;const bs=await allBanks();let pool=[];bs.forEach(b=>b.questions.forEach((q,i)=>{if(q.subject===s)pool.push({bankId:b.id,index:i})}));pool.sort(()=>Math.random()-.5);if(!pool.length)return toast("해당 과목 자료가 없습니다");startSession(`${subjects[s]} 랜덤`,pool.slice(0,20),1800)}
function startWrong(){if(!state.wrong.length)return toast("저장된 오답이 없습니다");startSession("오답 다시 풀기",[...state.wrong].sort(()=>Math.random()-.5),Math.max(1800,state.wrong.length*90))}
function remain(){return Math.max(0,state.session.seconds-Math.floor((Date.now()-state.session.startedAt)/1000))}
function clock(n){return `${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`}
async function quiz(){const s=state.session;if(!s)return route("banks");const ref=s.refs[s.current],bank=await getBank(ref.bankId),q=bank.questions[ref.index],chosen=s.answers[s.current];app.innerHTML=`<div class="quiz-top"><button class="secondary action" id="exit">나가기</button><div class="progress"><i style="width:${(s.current+1)/s.refs.length*100}%"></i></div><span class="timer" id="timer">${clock(remain())}</span></div><div class="question-meta"><b>${s.current+1}/${s.refs.length} · ${esc(q.subjectName||subjects[q.subject])}</b><span>${esc(bank.year)}-${esc(bank.round)} · ${q.number}번</span></div><img class="question-image" src="${q.question}" alt="${bank.label} ${q.number}번 문제"><div class="choices">${[1,2,3,4].map(n=>`<button class="choice ${chosen===n?'selected':''} ${chosen&&q.answer===n?'correct':''} ${chosen===n&&q.answer&&q.answer!==n?'wrong':''}" data-choice="${n}">${["①","②","③","④"][n-1]}</button>`).join("")}</div><div id="after">${chosen?feedback(q,chosen):""}</div><div class="quiz-actions"><button class="secondary" id="prev" ${s.current===0?'disabled':''}>이전</button><button class="primary" id="next">${s.current===s.refs.length-1?'제출':'다음'}</button></div>`;
app.querySelector("#exit").onclick=()=>route("home");app.querySelector("#prev").onclick=()=>{s.current--;save();quiz()};app.querySelector("#next").onclick=()=>{if(s.current===s.refs.length-1)finish();else{s.current++;save();quiz()}};app.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{s.answers[s.current]=Number(b.dataset.choice);save();quiz()});tick=setInterval(()=>{const t=document.querySelector("#timer");if(t)t.textContent=clock(remain());if(remain()===0)finish()},1000)}
function feedback(q,c){if(!q.answer)return `<div class="feedback"><b>정답표식 검수 대기</b><br><span class="muted">자동 채점에서 제외됩니다. 아래 원문 해설로 확인하세요.</span></div><img class="explanation-image" src="${q.explanation}" alt="원문 정답 및 해설">`;return `<div class="feedback"><b class="${c===q.answer?'':'danger'}">${c===q.answer?'정답입니다':'오답입니다 · 정답 '+["①","②","③","④"][q.answer-1]}</b></div><img class="explanation-image" src="${q.explanation}" alt="원문 정답 및 해설">`}
async function finish(){clearInterval(tick);const s=state.session,rows=[];for(let i=0;i<s.refs.length;i++){const r=s.refs[i],b=await getBank(r.bankId),q=b.questions[r.index],chosen=s.answers[i]||null;rows.push({ref:r,bank:b,q,chosen,correct:q.answer?chosen===q.answer:null})}const graded=rows.filter(x=>x.q.answer),correct=graded.filter(x=>x.correct).length,score=graded.length?Math.round(correct/graded.length*100):0;rows.forEach(x=>{const key=x.ref.bankId+":"+x.ref.index,at=state.wrong.findIndex(w=>w.bankId+":"+w.index===key);if(x.correct&&at>=0)state.wrong.splice(at,1);if(x.correct===false&&at<0)state.wrong.push(x.ref)});const rec={id:Date.now(),date:new Date().toISOString(),title:s.title,total:rows.length,graded:graded.length,correct,score,rows:rows.map(x=>({bankId:x.bank.id,year:x.bank.year,round:x.bank.round,number:x.q.number,subject:x.q.subjectName||subjects[x.q.subject],chosen:x.chosen,answer:x.q.answer,correct:x.correct}))};state.records.unshift(rec);state.session=null;save();route("result",rec)}
function markdown(r){const by=subjects.map(name=>{const a=r.rows.filter(x=>x.subject===name&&x.answer),c=a.filter(x=>x.correct).length;return `| ${name} | ${c}/${a.length} | ${a.length?Math.round(c/a.length*100):'-'} |`}).join("\n");const wrong=r.rows.filter(x=>x.correct===false).map(x=>`- ${x.year}년 ${x.round}회 ${x.number}번 / ${x.subject} / 선택 ${x.chosen||'미응답'} / 정답 ${x.answer}`).join("\n")||"- 없음";return `# 전기기사 학습 결과\n\n- 일시: ${new Date(r.date).toLocaleString('ko-KR')}\n- 모드: ${r.title}\n- 채점: ${r.correct}/${r.graded} (${r.score}점)\n- 검수 대기·채점 제외: ${r.total-r.graded}문항\n\n## 과목별\n\n| 과목 | 정답 | 정답률(%) |\n|---|---:|---:|\n${by}\n\n## 오답\n\n${wrong}\n\n## Codex 분석 요청\n\n위 오답 목록을 기준으로 취약 개념, 반복 실수, 우선 복습 과목을 분석해 줘. 문제 본문은 저작권 보호를 위해 포함하지 않았으며 필요하면 회차·번호로 내 개인 기출은행에서 확인할게.\n`}
function result(r){app.innerHTML=`<h1>채점 결과</h1><div class="card"><div class="result-score">${r.score}점</div><b>${r.correct}/${r.graded} 정답</b><p class="muted">전체 ${r.total}문항 중 정답표식 검수 대기 ${r.total-r.graded}문항은 점수에서 제외</p></div><h2>Codex · Notion용 Markdown</h2><textarea id="md">${esc(markdown(r))}</textarea><div class="grid"><button class="card primary" id="copy"><strong>Markdown 복사</strong></button><button class="card" id="download"><strong>.md 저장</strong></button><button class="card" id="notion"><strong>Notion 열기</strong></button><button class="card" data-view="home"><strong>홈으로</strong></button></div>`;app.querySelector("#copy").onclick=()=>navigator.clipboard.writeText(markdown(r)).then(()=>toast("복사했습니다"));app.querySelector("#download").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([markdown(r)],{type:"text/markdown"}));a.download=`전기기사-결과-${r.id}.md`;a.click()};app.querySelector("#notion").onclick=()=>window.open(state.notionUrl||"https://www.notion.so","_blank")}
function records(){app.innerHTML=`<h1>학습 기록</h1>${state.records.length?state.records.map(r=>`<button class="bank" data-record="${r.id}"><span><strong>${esc(r.title)}</strong><small>${new Date(r.date).toLocaleString('ko-KR')} · ${r.correct}/${r.graded}</small></span><span class="count">${r.score}</span></button>`).join(""):'<div class="notice">아직 기록이 없습니다.</div>'}`;app.querySelectorAll("[data-record]").forEach(x=>x.onclick=()=>result(state.records.find(r=>r.id===Number(x.dataset.record))))}
async function settings(){const bs=await allBanks();app.innerHTML=`<h1>개인정보·저장 설정</h1><div class="notice">기출 이미지는 이 브라우저의 IndexedDB에만 저장됩니다. 브라우저 데이터를 지우면 함께 삭제되므로 원본 .bank 파일을 보관하세요.</div><h2>Notion 연결</h2><input type="url" id="notion-url" value="${esc(state.notionUrl)}" placeholder="개인 오답노트 Notion 페이지 URL"><button class="action primary" id="save-notion">URL 저장</button><h2>저장된 회차</h2><div class="bank-list">${bs.map(b=>`<div class="bank"><span><strong>${esc(b.label)}</strong><small>${b.questions.length}문항</small></span><button class="action danger" data-delete="${esc(b.id)}">삭제</button></div>`).join("")}</div>`;app.querySelector("#save-notion").onclick=()=>{state.notionUrl=app.querySelector("#notion-url").value.trim();save();toast("저장했습니다")};app.querySelectorAll("[data-delete]").forEach(x=>x.onclick=async()=>{if(confirm("이 기기에서 해당 회차를 삭제할까요?")){await delBank(x.dataset.delete);settings()}})}
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");dday();route(state.session?"quiz":"home");
})();